const { Ship, GameBoard, Player } = require('./ship');

function placeShipsRandomly(gameBoard) {
    const shipLengths = [5, 4, 3, 3, 2];
    shipLengths.forEach(length => {
        let placed = false;
        while (!placed) {
            const axis = Math.random() > 0.5 ? 'horizontal' : 'vertical';
            const x = Math.floor(Math.random() * 10);
            const y = Math.floor(Math.random() * 10);
            const ship = new Ship("RandomShip", length);
            placed = gameBoard.addShip(ship, x, y, axis);
        }
    });
}

function load(){
document.addEventListener('DOMContentLoaded', function () {
    const placingBoard = document.querySelector('.placing-board');
    const playerBoard = document.querySelector('.player-board');
    const computerBoard = document.querySelector('.computer-board');
    const startBtn = document.getElementById('start-btn');
    const resetBtn = document.getElementById('reset-btn');
    const randomBtn = document.getElementById('random-btn');
    const gameStatus = document.querySelector('.game-status');
    const playerGameBoard = new GameBoard();
    const computerGameBoard = new GameBoard();

    function createBoard(boardElement, gameBoard) {
        boardElement.innerHTML = '';

        // const gameBoard = new GameBoard();
        placeShipsRandomly(gameBoard);

        for (let i = 0; i < 10; i++) {
            for (let j = 0; j < 10; j++) {
                const cell = document.createElement('div');
                cell.className = 'cell';
                cell.dataset.row = j;
                cell.dataset.col = i;
                cell.classList.remove = 'ship';

                const ship = gameBoard.ships[i][j];
                if (ship !== 0 && ship !== 1) {
                    cell.classList.add('ship');
                }

                boardElement.appendChild(cell);
            }
        }
    }

    function initializeGame() {
        // Initialize placing board
        // createBoard(placingBoard);
        createBoard(playerBoard, playerGameBoard);
        createBoard(computerBoard, computerGameBoard);
        
    }




    // Initialize boards
    // createBoard(playerBoard, true);
    // createBoard(computerBoard, false);
    initializeGame();

    // Add event listeners for game controls
    startBtn.addEventListener('click', function () {
        gameStatus.textContent = "RADAR ACTIVE - ENGAGE ENEMY TARGETS";
        startBtn.disabled = true;

        // Add click handlers to computer board for gameplay
        const computerCells = document.querySelectorAll('.computer-board .cell');
        computerCells.forEach(cell => {
            cell.addEventListener('click', function () {
                if (!this.classList.contains('hit') && !this.classList.contains('miss')) {
                    if (this.classList.contains('ship') && computerGameBoard.reciveAttack(parseInt(this.dataset.col), parseInt(this.dataset.row))) {
                        this.classList.add('hit');
                        gameStatus.textContent = "DIRECT HIT! ENEMY VESSEL DAMAGED!";
                        if(computerGameBoard.allSunk()) {
                            gameStatus.textContent = "ALL ENEMY VESSELS DESTROYED - VICTORY ACHIEVED!";
                        }
                    } else {
                        this.classList.add('miss');
                        gameStatus.textContent = "TARGET MISSED - RECALIBRATING";
                    }
                }
            });
        });
    });

    resetBtn.addEventListener('click', function () {
        createBoard(playerBoard, true);
        createBoard(computerBoard, false);
        gameStatus.textContent = "SYSTEMS RESET - DEPLOY YOUR FLEET";
        startBtn.disabled = false;
    });

    // randomBtn.addEventListener('click', function () {
    //     createBoard(playerBoard, true);
    //     gameStatus.textContent = "RANDOM DEPLOYMENT COMPLETE - ACTIVATE RADAR";
    // });
});
}
module.exports =  {load, placeShipsRandomly};
//  <div class="container">
//       <header>
//         <h1>BATTLESHIP</h1>
//         <div class="game-status">
//           ACTIVATE RADAR SYSTEMS - DEPLOY YOUR FLEET
//         </div>
//       </header>

//       <div class="game-boards">
//         <div class="board-container">
//           <h2 class="board-title">FRIENDLY FLEET</h2>
//           <div class="coordinates">
//             <div class="coordinate">A</div>
//             <div class="coordinate">B</div>
//             <div class="coordinate">C</div>
//             <div class="coordinate">D</div>
//             <div class="coordinate">E</div>
//             <div class="coordinate">F</div>
//             <div class="coordinate">G</div>
//             <div class="coordinate">H</div>
//             <div class="coordinate">I</div>
//             <div class="coordinate">J</div>
//           </div>
//           <div class="game-board player-board">
//             <!-- Player board cells will be generated by JavaScript -->
//           </div>
//         </div>

//         <div class="board-container">
//           <h2 class="board-title">ENEMY WATERS</h2>
//           <div class="coordinates">
//             <div class="coordinate">A</div>
//             <div class="coordinate">B</div>
//             <div class="coordinate">C</div>
//             <div class="coordinate">D</div>
//             <div class="coordinate">E</div>
//             <div class="coordinate">F</div>
//             <div class="coordinate">G</div>
//             <div class="coordinate">H</div>
//             <div class="coordinate">I</div>
//             <div class="coordinate">J</div>
//           </div>
//           <div class="game-board computer-board">
//             <!-- Computer board cells will be generated by JavaScript -->
//           </div>
//         </div>
//       </div>

//       <div class="controls">
//         <button id="start-btn">ACTIVATE RADAR</button>
//         <button id="reset-btn">RESET SYSTEMS</button>
//       </div>

//       <div class="instructions">
//         <h2>TACTICAL BRIEFING</h2>
//         <ul>
//           <li>Deploy your fleet on your tactical grid</li>
//           <li>Activate radar systems to begin engagement</li>
//           <li>Target enemy coordinates by selecting grid positions</li>
//           <li>Red markers indicate successful hits on enemy vessels</li>
//           <li>Gray markers indicate missed targets</li>
//           <li>Eliminate all enemy ships to achieve victory</li>
//         </ul>
//       </div>
//     </div>
// \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\


    // <div class="initial-ui">
    //   <h1>WELCOME TO BATTLESHIP</h1>
    //   <h3>Place You Carrier:</h3>

    //   <div class="game-boards initial-board">
    //     <div class="board-container">
    //       <div class="coordinates">
    //         <div class="coordinate">A</div>
    //         <div class="coordinate">B</div>
    //         <div class="coordinate">C</div>
    //         <div class="coordinate">D</div>
    //         <div class="coordinate">E</div>
    //         <div class="coordinate">F</div>
    //         <div class="coordinate">G</div>
    //         <div class="coordinate">H</div>
    //         <div class="coordinate">I</div>
    //         <div class="coordinate">J</div>
    //       </div>
    //       <div class="game-board placing-board">
    //         <!-- Player board cells will be generated by JavaScript -->
    //       </div>
    //     </div>
    //     <div><button id="random-btn">RANDOM DEPLOYMENT</button></div>
          
    //   </div>
    // </div>